export enum Profissao {
    ELETRICISTA = 'ELETRICISTA',
    MECANICO = 'MECANICO',
    MARCENEIRO = 'MARCENEIRO',
    CHAPEADOR = 'CHAPEADOR',
    JARDINEIRO = 'JARDINEIRO',
    CARPINTEIRO = 'CARPINTEIRO',
    CONTADOR = 'CONTADOR',
    ENCANADOR = 'ENCANADOR',
    METALURGICO = 'METALURGICO',
    NUTRICIONISTA = 'NUTRICIONISTA',
    OUTROS = 'OUTROS'
}